
#ifndef _DEV_IOCTL_H 
#define _DEV_IOCTL_H

//ioctl code
/*=======================SDIO=========================*/
#define IOCTL_SDIO_FBR_ACCESS_READ \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xEb0, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_SDIO_FBR_ACCESS_WRITE \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xEb1, METHOD_BUFFERED, FILE_ANY_ACCESS )
/*=======================SDIO=========================*/


#define IOCTL_QA_SEND_FW_CMD  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD19, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_USBQA_USB_EEPROM_READ  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD24, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_USBQA_USB_EEPROM_WRITE  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD25, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_FWD_SEQNUM \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD1B, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_FWD_STATUS \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD1C, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_PACKETCMD_SEQNUM \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD1D, METHOD_BUFFERED, FILE_ANY_ACCESS )    
#define IOCTL_GET_PACKETCMD_RESPONSE \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD1E, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_EEPROM_READ  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD67, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_EEPROM_WRITE \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD68, METHOD_BUFFERED, FILE_ANY_ACCESS )

/////////////////////////////////////////////////////////////////////////////

#define IOCTL_QA_Select_Interface	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD7F, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_QA_CMD_Send	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD80, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_QA_CMD_Receive	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD81, METHOD_BUFFERED, FILE_ANY_ACCESS )
	    
#define IOCTL_QA_Enable_Ready	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD82, METHOD_BUFFERED, FILE_ANY_ACCESS )

/////////////////////////////////////////////////////////////////////////////

#define IOCTL_ENABLE_BEACON	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDb0, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_DISABLE_BEACON	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDb1, METHOD_BUFFERED, FILE_ANY_ACCESS )
	    
// set TCP/IP payload
#define IOCTL_SET_TCPIP_PAYLOAD	\
	    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDb2, METHOD_BUFFERED, FILE_ANY_ACCESS )

//USB
#define BULKUSB_IOCTL_INDEX             0x0000


#define IOCTL_BULKUSB_GET_CONFIG_DESCRIPTOR CTL_CODE(FILE_DEVICE_UNKNOWN,     \
                                                     BULKUSB_IOCTL_INDEX,     \
                                                     METHOD_BUFFERED,         \
                                                     FILE_ANY_ACCESS)
                                                   
#define IOCTL_BULKUSB_RESET_DEVICE          CTL_CODE(FILE_DEVICE_UNKNOWN,     \
                                                     BULKUSB_IOCTL_INDEX + 1, \
                                                     METHOD_BUFFERED,         \
                                                     FILE_ANY_ACCESS)

#define IOCTL_BULKUSB_RESET_PIPE            CTL_CODE(FILE_DEVICE_UNKNOWN,     \
                                                     BULKUSB_IOCTL_INDEX + 2, \
                                                     METHOD_BUFFERED,         \
                                                     FILE_ANY_ACCESS)

#define IOCTL_MAC_READ_LONG  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD20, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_MAC_READ_LONG63  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD63, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_MAC_READ_LONG47  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD47, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_MAC_WRITE_LONG  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD21, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_MAC_WRITE_LONG66  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD66, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_SETUP_TX_PACKET \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD93, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_START_TX \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD94, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_STOP_TX \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD92, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_START_RX0  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD98, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_STOP_RX0  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xD99, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_START_RX1  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa0, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_STOP_RX1  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa1, METHOD_BUFFERED, FILE_ANY_ACCESS )

//common
#define IOCTL_HAL_CMD  \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa2, METHOD_BUFFERED, FILE_ANY_ACCESS )

//EEPROM or buffer bin or eFuse data
#define IOCTL_WRITE_EEPROM_BUFFER \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa3, METHOD_BUFFERED, FILE_ANY_ACCESS ) 

#define IOCTL_SET_EFUSE_MODE \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa4, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_RESET_TXRX_COUNTER \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa5, METHOD_BUFFERED, FILE_ANY_ACCESS )
    
//Write FW
#define IOCTL_WRITE_FW \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa6, METHOD_BUFFERED, FILE_ANY_ACCESS )    

//Clear FW
#define IOCTL_CLEAR_FW \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa7, METHOD_BUFFERED, FILE_ANY_ACCESS )    

//Download FW
#define IOCTL_DOWNLOAD_FW \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0xDa8, METHOD_BUFFERED, FILE_ANY_ACCESS )
    
NTSTATUS DevIoctlHandler(RTMP_ADAPTER *pAdapter, UINT32 inputBufferLength, PVOID inBuffer, UINT32 outputBufferLength, PVOID outBuffer, UINT32 ioControlCode, UINT32 *ByteRet);


#endif //_DEV_IOCTL_H
